services:
  backend-dj:
    container_name: backend-dj
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - DEBUG=False
    depends_on:
      - db-postgres

  frontend-react:
    container_name: frontend-react
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend-dj

  db-postgres:
    container_name: db-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"

  mkdocs:
    container_name: mkdocs
    build:
      context: ./docs
    ports:
      - "${MKDOCS_PORT}:8000"
    volumes:
      - ./docs:/app

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki

  loki:
    container_name: loki
    image: grafana/loki:2.9.3
    ports:
      - "${LOKI_PORT}:3100"
    volumes:
      - ./monitoring/loki:/etc/loki
      - ./monitoring/loki/index:/loki/index
      - ./monitoring/loki/cache:/loki/cache
      - ./monitoring/loki/chunks:/loki/chunks
      - ./monitoring/loki/filesystem:/loki/filesystem
      - ./monitoring/loki/wal:/loki/wal
      - ./monitoring/loki/compactor:/loki/compactor
    command: -config.file=/etc/loki/loki-config.yaml

  logging-promtail:
    container_name: logging-promtail
    image: grafana/promtail:2.9.3
    volumes:
      - ./logging/promtail:/etc/promtail
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki

volumes:
  postgres_data:
  loki-data:
